# Generated by Django 2.2 on 2019-09-15 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20190914_1253'),
        ('estudiantes', '0002_auto_20190914_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planificador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Horario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='planificadores',
            field=models.ManyToManyField(blank=True, null=True, to='estudiantes.Planificador'),
        ),
    ]
