# Generated by Django 2.2 on 2019-09-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_auto_20190915_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planificador',
            options={'verbose_name': 'Planificador', 'verbose_name_plural': 'Planificadores'},
        ),
    ]
