# Generated by Django 2.2 on 2019-09-16 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_auto_20190916_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='planificadores',
        ),
        migrations.AddField(
            model_name='planificador',
            name='estudiante',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Estudiante'),
            preserve_default=False,
        ),
    ]
