# Generated by Django 2.2 on 2019-09-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, null=True, to='estudiantes.Estudiante'),
        ),
    ]
